# derivations for node.js-based applications in NixOS are supposed to be generated by node2nix
{ stdenv, pkgs, fetchurl, fetchzip, ...}@args:
let
in
stdenv.mkDerivation {
  name = "op-energy-client";

  src = ./.;
  buildInputs = with pkgs;
  [ op-energy-api
    swagger-codegen
  ];
  preConfigure = ''
  '';
  buildPhase = ''
    mkdir -p $out
    ${pkgs.op-energy-api}/bin/op-energy-api > ./swagger.json
    swagger-codegen generate -l typescript-angular -c config.json -i swagger.json -o $out
  '';
  installPhase = ''
    true
  '';
}
