name: "Op-Energy backend"
on:
  pull_request:
    types: [opened, ready_for_review, synchronize, workflow_dispatch]
jobs:
  test_build:
    uses: ./.github/workflows/test.yml
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
