name: "Op-Energy backend"
on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-22.05
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: git clone https://github.com/dambaev/op-energy-development.git ../op-energy-development --recursive
    # current repo's use case is to be submodule in 80% of cases, so we need to copy content of op-energy repo into a proper submodule location
    - run: rm -rf ../op-energy-development/overlays/ope-blockspan-service/* && cp -r $(pwd)/* ../op-energy-development/overlays/ope-blockspan-service/
    # ci-tests.nix should be on the same level as op-energy-development
    - run: cp ci-tests.nix ../
    # now actually run the builds and tests with passing git commit hash as an argument
    - run: cd ../ && nix-build ci-tests.nix --argstr GIT_COMMIT_HASH $( echo ${{github.sha}} | cut -c 1-8 )

